---
title: "9/13 class"
author: "Cole Bennett"
date: '2023-09-13'
output: html_document
---
```{r}
library(here)
library(tidyverse)
library(janitor)
```


```{r}
file2017 = here("data_raw", "DL_SelectFields_2017.zip")

file2018 = here("data_raw", "DL_SelectFields_2018.zip")

file2019 = here("data_raw", "DL_SelectFields_2019.zip")

file2020 = here("data_raw", "DL_SelectFields_2020.zip")

file2021 = here("data_raw", "DL_SelectFields_2021.zip")

file2022 = here("data_raw", "DL_SelectFields_2022.zip")

file2023 = here("data_raw", "DL_SelectFields_2023.zip")

file_combined = c(file2017, file2018, file2019, file2020, file2021, file2022, file2023)

df_combined = read_csv(file_combined) %>% clean_names
```


```{r}
df1  = df_combined |> mutate(month_year = month+year*12)

df1 |> ggplot(aes(month_year)) + geom_bar(aes(weight = passengers))
```

```{r}
df2 <- df1 |> filter( (origin == "MIA" & dest == "LGA") | (origin == "LGA" & dest == "MIA") )
```


```{r}
df2 |> ggplot(aes(month_year)) + geom_bar(position = position_dodge(), aes(weight = passengers, fill = origin))
```
```{r}
df3 <- df2 |> group_by(origin, month_year)|>
  summarise(count = sum(passengers))|> mutate(cumulative_count = cumsum(count)) |>
  pivot_wider(names_from = origin, values_from = c(count, cumulative_count))|> mutate(difference = count_LGA - count_MIA, cumulative_difference = cumulative_count_LGA - cumulative_count_MIA)
```

```{r}
df3 |> ggplot(aes(x = month_year, y = difference)) +
  geom_point()

df3 |> ggplot(aes(x = month_year, y = cumulative_difference)) +
  geom_line()
```

